### ISSUE TITLE
微软面试有英文面吗

### ISSUE THREAD

**Issue by ZWJzhangwanjie** [JD331/JD331#6]

**Comment by ZWJzhangwanjie** [comment]
危险

**Comment by vacuume** [comment]
趁着还有京东邮箱，可以开通老虎证券并认证为京东员工，可以领100元E卡和50元微信红包
京东员工开户链接：
https://www.itigergrowth.com/activity/forapp/corporate-benefits?group_id=137&invite=JD123
或者自行开户使用邀请码【JD123】
还有一年免佣以及终身免佣的活动，最近不用以后也会用到的。
